/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsRegionalSteelWorksRouteImport } from './routes/locations/regionalSteelWorks'
import { Route as LocationsPrecisionManufacturingLLCRouteImport } from './routes/locations/precisionManufacturingLLC'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRegionalSteelWorksRoute =
  LocationsRegionalSteelWorksRouteImport.update({
    id: '/locations/regionalSteelWorks',
    path: '/locations/regionalSteelWorks',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsPrecisionManufacturingLLCRoute =
  LocationsPrecisionManufacturingLLCRouteImport.update({
    id: '/locations/precisionManufacturingLLC',
    path: '/locations/precisionManufacturingLLC',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/locations/precisionManufacturingLLC': typeof LocationsPrecisionManufacturingLLCRoute
  '/locations/regionalSteelWorks': typeof LocationsRegionalSteelWorksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/locations/precisionManufacturingLLC': typeof LocationsPrecisionManufacturingLLCRoute
  '/locations/regionalSteelWorks': typeof LocationsRegionalSteelWorksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/locations/precisionManufacturingLLC': typeof LocationsPrecisionManufacturingLLCRoute
  '/locations/regionalSteelWorks': typeof LocationsRegionalSteelWorksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/locations/precisionManufacturingLLC'
    | '/locations/regionalSteelWorks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/locations/precisionManufacturingLLC'
    | '/locations/regionalSteelWorks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/locations/precisionManufacturingLLC'
    | '/locations/regionalSteelWorks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LocationsPrecisionManufacturingLLCRoute: typeof LocationsPrecisionManufacturingLLCRoute
  LocationsRegionalSteelWorksRoute: typeof LocationsRegionalSteelWorksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/regionalSteelWorks': {
      id: '/locations/regionalSteelWorks'
      path: '/locations/regionalSteelWorks'
      fullPath: '/locations/regionalSteelWorks'
      preLoaderRoute: typeof LocationsRegionalSteelWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/precisionManufacturingLLC': {
      id: '/locations/precisionManufacturingLLC'
      path: '/locations/precisionManufacturingLLC'
      fullPath: '/locations/precisionManufacturingLLC'
      preLoaderRoute: typeof LocationsPrecisionManufacturingLLCRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LocationsPrecisionManufacturingLLCRoute:
    LocationsPrecisionManufacturingLLCRoute,
  LocationsRegionalSteelWorksRoute: LocationsRegionalSteelWorksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
